### ISSUE TITLE
LUA errors with version 10.0.0.2-alpha

### ISSUE THREAD

**Issue by fraerie** [Xuerian/XLoot#10]
Multiple errors

2x Interface/AddOns/XLoot_Frame/Frame.lua:525: attempt to call global 'LootButton_OnClick' (a nil value)
[string "@Interface/AddOns/XLoot_Frame/Frame.lua"]:525: in function <Interface/AddOns/XLoot_Frame/Frame.lua:520>

Locals:
self = XLootFrameButton1 {
 0 = <userdata>
 OnEnter = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:507
 ShowHighlight = <function> defined @Interface/AddOns/XLoot/skins.lua:232
 text_info = FontString {
 }
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 Auto_OnLeave = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:548
 i = 1
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 RightEdge = Texture {
 }
 texture_item = XLootFrameButton1IconTexture {
 }
 layout = "simple"
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 HighlightLeave = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:501
 gradient = Texture {
 }
 HighlightEnter = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:495
 text_locked = FontString {
 }
 Update = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:635
 _SetBorderColor = <function> defined @Interface/AddOns/XLoot/skins.lua:170
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 GetBorderColor = <function> defined @Interface/AddOns/XLoot/skins.lua:176
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 _skin_options = <table> {
 }
 slot = 1
 TopEdge = Texture {
 }
 owner = XLootFrame {
 }
 Auto_OnShow = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:553
 button_auto = Button {
 }
 OffsetText = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:458
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 _highlights = <table> {
 }
 _skin_borders = <table> {
 }
 _higlight_options = <table> {
 }
 HideHighlight = <function> defined @Interface/AddOns/XLoot/skins.lua:238
 ShowTooltip = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:490
 Auto_OnClick = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:530
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 OnClick = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:520
 quality = 0
 BottomEdge = Texture {
 }
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 SetBorderColor = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:463
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 text_button_auto = FontString {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 frame_slot = 1
 Auto_OnHide = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:557
 Center = Texture {
 }
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 item_name = "Twisted Sediment"
 UpdateAppearance = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:563
 backdropInfo = <table> {
 }
 BottomLeftCorner = Texture {
 }
 OnLeave = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:513
 TopLeftCorner = Texture {
 }
 SetHighlightColor = <function> defined @Interface/AddOns/XLoot/skins.lua:244
 text_quantity = FontString {
 }
 texture_bang = Texture {
 }
 BottomRightCorner = Texture {
 }
 text_bind = FontString {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 text_name = XLootFrameButton1Text {
 }
 Auto_OnEnter = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:541
 SetGradientColor = <function> defined @Interface/AddOns/XLoot/skins.lua:180
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 GetHighlightColor = <function> defined @Interface/AddOns/XLoot/skins.lua:250
 frame_item = Frame {
 }
 TopRightCorner = Texture {
 }
}
button = "LeftButton"
(*temporary) = nil
(*temporary) = XLootFrameButton1 {
 0 = <userdata>
 OnEnter = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:507
 ShowHighlight = <function> defined @Interface/AddOns/XLoot/skins.lua:232
 text_info = FontString {
 }
 OnBackdropLoaded = <function> defined @

1x Interface/AddOns/XLoot_Options/Options.lua:769: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: in function `ipairs'
[string "@Interface/AddOns/XLoot_Options/Options.lua"]:769: in function `OpenPanel'
[string "@Interface/AddOns/XLoot/XLoot.lua"]:56: in function `ShowOptionPanel'
[string "@Interface/AddOns/XLoot/XLoot.lua"]:145: in function <Interface/AddOns/XLoot/XLoot.lua:145>
[string "=[C]"]: in function `Show'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:803: in function `DisplayLayout'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:758: in function `DisplayCategory'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:725: in function <...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:721>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:143: in function <Interface/SharedXML/CallbackRegistry.lua:142>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:146: in function `TriggerEvent'
[string "@Interface/SharedXML/Settings/Blizzard_CategoryList.lua"]:136: in function <...terface/SharedXML/Settings/Blizzard_CategoryList.lua:134>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by Xuerian** [comment]
Thanks.

The first one should be fixed in -3, I think. Please let me know.

The second one is going to require more work, options may take a while.

**Comment by Xuerian** [comment]
Options should be fixed now. Thanks for the report.
