### ISSUE TITLE
Issue after Stage 2 Expansion Pre Patch

### ISSUE THREAD

**Issue by Viperk8b** [Xuerian/XLoot#13]
Loot Window is no longer appearing after newest pre-patch.

36x Interface/AddOns/XLoot_Frame/Frame.lua:1225: attempt to call global 'GetContainerNumFreeSlots' (a nil value)
[string "@Interface/AddOns/XLoot_Frame/Frame.lua"]:1225: in function `Update'
[string "@Interface/AddOns/XLoot_Frame/Frame.lua"]:1320: in function `?'
[string "@Interface/AddOns/XLoot/XLoot.lua"]:39: in function <Interface/AddOns/XLoot/XLoot.lua:37>

Locals:
self = XLootFrame {
 0 = <userdata>
 Highlight = <function> defined @Interface/AddOns/XLoot/skins.lua:358
 close = XLootFrameClose {
 }
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 GetColor = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:424
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 UpdateWidth = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:928
 opt = <table> {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 SnapToCursor = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:843
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 Reskin = <function> defined @Interface/AddOns/XLoot/skins.lua:328
 rows = <table> {
 }
 Update = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:1142
 LinkClick = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:884
 auto_items = <table> {
 }
 built = true
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 skin = <table> {
 }
 UpdateAppearance = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:970
 slots = <table> {
 }
 slots_index = <table> {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 old_close = Button {
 }
 link = XLootFrameLink {
 }
 addon = <table> {
 }
 overlay = Frame {
 }
 SizeAndColor = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:956
 Skin = <function> defined @Interface/AddOns/XLoot/skins.lua:349
 UpdateHeight = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:918
 _skin_data = <table> {
 }
 UpdateLinkButton = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:936
 ParseAutolootList = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:1103
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 row_height = 33
 OnHide = <function> defined @Interface/AddOns/XLoot_Frame/Frame.lua:892
}
no_snap = nil
is_refresh = nil
numloot = 4
max = <function> defined =[C]:-1
rows = <table> {
 1 = XLootFrameButton1 {
 }
 2 = XLootFrameButton2 {
 }
}
slots = <table> {
}
slots_index = <table> {
}
bag_slots = <table> {
}
auto = <table> {
 tradegoods = true
 currency = true
 list = true
 all = false
 quest = true
}
auto_items = <table> {
 Briarthorn = true
 Bruiseweed = true
 Kingsblood = true
 Liferoot = true
 Khadgar's Whisker = true
 Swiftthistle = true
 Springy Eyeball = true
 Relic of Ulduar = true
 Silk Cloth = true
 Fadeleaf = true
 Worn Junkbox = true
 Goldthorn = true
 Mageroyal = true
 Wild Steelbloom = true
 Linen Cloth = true
}
max_quality = 0
max_width = 0
our_slot = 0
slot = nil
need_refresh = true
(for index) = 2
(for limit) = 4
(for step) = 1
slot = 2
_ = true
icon = 132911
name = "Wool Cloth"
quantity = 1
currencyID = nil
quality = 1
locked = false
isQuestItem = false
questID = nil
startsQuest = nil
autoloot = false
slotType = 1
slotData = <table> {
 equipLoc = ""
 subTypeName = "Cloth"
 sellPrice = 33
 bindType = 0
 typeID = 7
 slotType = 1
 stackCount = 1000
 level = 10
 icon = 132911
 quality = 1
 link = "|cffffffff|Hitem:2592::::::::60:263:::::::::|h[Wool Cloth]|h|r"
 subTypeID = 5
 isCraftingReagent = true
 minLevel = 0
 questItem = false
 locked = false
 quantity = 1
 typeName = "Tradeskill"
 name = "Wool Cloth"
}
(for index) = 0
(for limit) = 4
(for step) = 1
i = 0
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call global 'GetContainerNumFreeS

**Comment by Xuerian** [comment]
This should be addressed in 10.0.2-1
