### ISSUE TITLE
API update with Ulduar Patch

### ISSUE THREAD

**Issue by zeress** [Xuerian/XLoot#15]
The loot roll window (display item and select need or greed) seem to no longer display with the Ulduar patch update on Wrath Classic.

Just thought you should know, if you weren't already aware.

**Comment by Xuerian** [comment]
Please verify you are using [10.0.2-2](https://www.wowace.com/projects/xloot/files/4238494), it was not flagged for classic until earlier today.

**Comment by zeress** [comment]
It seems to now be working with -2, thank you for the speedy update!
