### ISSUE TITLE
Xloot is not showing loot window any more

### ISSUE THREAD

**Issue by Dan-Gecko** [Xuerian/XLoot#21]
I am experiencing a problem with XLoot: It's not showing the looting window any more. I am not sure what I did exactly. I was playing around with a few options, fonts and the background settings. I don't care really if it gets fixed as long as somebody tells me how to revert changes that possibly caused the error and lets me use my fav. looting addon once again. Thanks!

this is the error I am getting: 
`3x XLoot/skins.lua:181: attempt to call method 'SetGradientAlpha' (a nil value)
[string "@XLoot/skins.lua"]:181: in function `SetGradientColor'
[string "@XLoot/skins.lua"]:192: in function `Gradient'
[string "@XLoot/skins.lua"]:213: in function `Skin'
[string "@XLoot/skins.lua"]:351: in function `Skin'
[string "@XLoot_Group/Group.lua"]:134: in function <XLoot_Group/Group.lua:95>
[string "=[C]"]: ?`

PS: sorry I am not using ace but I will certainly never sign up for curseforge. 

EDIT1: there's a lot more log text with different errors there I can post if necessary.

**Comment by Xuerian** [comment]
Let me know if this is still occurring.

**Comment by Dan-Gecko** [comment]
tyvm!! it seems fixed now.
