### ISSUE TITLE
Cata Pre-Patch error

### ISSUE THREAD

**Issue by frenzypagle** [Xuerian/XLoot#28]
With the Cata pre-patch that dropped today XLoot is reporting this error:

Message: Interface/AddOns/XLoot/stacks.lua line 148:
   bad argument #1 to 'SetJustifyH' (Usage: self:SetJustifyH(justifyH))

I was able to fix locally by changing https://github.com/Xuerian/XLoot/blob/master/stacks.lua#L148 to 

```lua
label:SetJustifyH('CENTER')
```

**Comment by frenzypagle** [comment]
Similar changes are also needed on https://github.com/Xuerian/XLoot/blob/master/Modules/Frame/Frame.lua#L1061-L1067

**Comment by Xuerian** [comment]
Thank you for the report and the fixes, let me know if that doesn't fix the issue.
