### ISSUE TITLE
Xloot Not Working on Cataclysm Classic V4.4.0

### ISSUE THREAD

**Issue by RoMy066** [Xuerian/XLoot#29]
Hi,

Xloot Not working on Cataclysm Version V4.4.0

Message: Interface/AddOns/XLoot/stacks.lua:148: bad argument #1 to 'SetJustifyH' (Usage: self:SetJustifyH(justifyH))
Time: Wed May  1 18:40:49 2024
Count: 1
Stack: Interface/AddOns/XLoot/stacks.lua:148: bad argument #1 to 'SetJustifyH' (Usage: self:SetJustifyH(justifyH))
[string "=[C]"]: in function `SetJustifyH'
[string "@Interface/AddOns/XLoot/stacks.lua"]:148: in function `CreateAnchor'
[string "@Interface/AddOns/XLoot/stacks.lua"]:213: in function `CreateStaticStack'
[string "@Interface/AddOns/XLoot_Group/Group.lua"]:131: in function <Interface/AddOns/XLoot_Group/Group.lua:99>
[string "=[C]"]: ?
[string "@Interface/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...face/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...face/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/XLoot/XLoot.lua"]:148: in function <Interface/AddOns/XLoot/XLoot.lua:136>
[string "=[C]"]: ?
[string "@Interface/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...face/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...face/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: (*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = "MIDDLE"

Message: Interface/AddOns/XLoot/stacks.lua:148: bad argument #1 to 'SetJustifyH' (Usage: self:SetJustifyH(justifyH))
Time: Wed May  1 18:40:49 2024
Count: 1
Stack: Interface/AddOns/XLoot/stacks.lua:148: bad argument #1 to 'SetJustifyH' (Usage: self:SetJustifyH(justifyH))
[string "=[C]"]: in function `SetJustifyH'
[string "@Interface/AddOns/XLoot/stacks.lua"]:148: in function `CreateAnchor'
[string "@Interface/AddOns/XLoot/stacks.lua"]:213: in function `CreateStaticStack'
[string "@Interface/AddOns/XLoot_Monitor/Monitor.lua"]:93: in function <Interface/AddOns/XLoot_Monitor/Monitor.lua:79>
[string "=[C]"]: ?
[string "@Interface/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...face/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...face/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/XLoot/XLoot.lua"]:148: in function <Interface/AddOns/XLoot/XLoot.lua:136>
[string "=[C]"]: ?
[string "@Interface/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...face/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...face/AddOns/XLoot/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: (*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = "MIDDLE"

**Comment by NayooZ** [comment]
Change line 148 in stacks.lua from MIDDLE to CENTER

**Comment by RoMy066** [comment]
Works thx

**Comment by NayooZ** [comment]
Also may need to change line 926 in Frame.lua to CENTER as well

**Comment by Xuerian** [comment]
This is fixed in source and I'm trying to see why curseforge isn't packaging it.

**Comment by Xuerian** [comment]
Should be fixed in 10.1-2b which is pending on Curseforge.
