### ISSUE TITLE
XLoot throwing errors with 10.2.7

### ISSUE THREAD

**Issue by fraerie** [Xuerian/XLoot#30]
7x XLoot/stacks.lua:148: bad argument #1 to 'SetJustifyH' (Usage: self:SetJustifyH(justifyH))
[string "=[C]"]: in function `SetJustifyH'
[string "@XLoot/stacks.lua"]:148: in function `CreateAnchor'
[string "@XLoot/stacks.lua"]:213: in function `CreateStaticStack'
[string "@XLoot_Monitor/Monitor.lua"]:93: in function <XLoot_Monitor/Monitor.lua:79>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@XLoot/XLoot.lua"]:148: in function <XLoot/XLoot.lua:136>
[string "=[C]"]: ?
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:607: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
(*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = "MIDDLE"

**Comment by Xuerian** [comment]
Are you using the latest version? https://www.curseforge.com/wow/addons/xloot/files/5308684

**Comment by fraerie** [comment]
it looks like I missed the most recent update - have updated and will let you know if it errors
