### ISSUE TITLE
Frame error hides loot window

### ISSUE THREAD

**Issue by Zasz333** [Xuerian/XLoot#32]
XLoot_Frame/Frame.lua:926: bad argument #1 to 'SetJustifyH' (Usage: self:SetJustifyH(justifyH))
[string "=[C]"]: in function `SetJustifyH'
[string "@XLoot_Frame/Frame.lua"]:926: in function <XLoot_Frame/Frame.lua:921>
[string "@XLoot_Frame/Frame.lua"]:1061: in function `BuildLootFrame'
[string "@XLoot_Frame/Frame.lua"]:1169: in function `Update'
[string "@XLoot_Frame/Frame.lua"]:1340: in function `?'
[string "@XLoot/XLoot.lua"]:41: in function <XLoot/XLoot.lua:39>

Locals:
(*temporary) = XLootFrameLinkText {
 0 = <userdata>
}
(*temporary) = "MIDDLE"

**Comment by Xuerian** [comment]
Are you using the latest version? https://www.curseforge.com/wow/addons/xloot/files/5308684

**Comment by Zasz333** [comment]
Ah, thanks. I didnt notice that the curse app didnt list xloot in the list anymore. No clue why. Reinstalled and works again. Thanks.
