### ISSUE TITLE
War within beta errors

### ISSUE THREAD

**Issue by Axejess** [Xuerian/XLoot#34]
1:
Message: Interface/AddOns/XLoot_Frame/Frame.lua:229: attempt to call global 'GetItemInfo' (a nil value)
Time: Fri Jun 14 13:14:47 2024
Count: 1
Stack: Interface/AddOns/XLoot_Frame/Frame.lua:229: attempt to call global 'GetItemInfo' (a nil value)

Locals: 

2:
Message: Interface/AddOns/XLoot_Group/Group.lua:1015: attempt to call global 'GetItemInfo' (a nil value)
Time: Fri Jun 14 13:14:47 2024
Count: 1
Stack: Interface/AddOns/XLoot_Group/Group.lua:1015: attempt to call global 'GetItemInfo' (a nil value)

Locals:

3:
Message: Interface/AddOns/XLoot_Monitor/Monitor.lua:445: attempt to call global 'GetItemInfo' (a nil value)
Time: Fri Jun 14 13:14:47 2024
Count: 1
Stack: Interface/AddOns/XLoot_Monitor/Monitor.lua:445: attempt to call global 'GetItemInfo' (a nil value)

Locals:

**Comment by Xuerian** [comment]
Let me know what else breaks and if that doesn't fix it.
