### ISSUE TITLE
Packaging error since version 10.1-3

### ISSUE THREAD

**Issue by Shauren** [Xuerian/XLoot#36]
Installing either from curse client or downloading raw zip file from curseforge is missing all module addons 

10.1-3:
![obraz](https://github.com/Xuerian/XLoot/assets/297439/c9f7fe70-2bd8-43fd-ada2-c5b967b80d8e)

10.1-2b
![obraz](https://github.com/Xuerian/XLoot/assets/297439/a1711e87-b790-4491-83ee-5a4c1510977e)

**Comment by ldene** [comment]
this would explain why the command /xloot doesn't work and it doesn't appear in options -> addons, so can't configure anything

**Comment by Xuerian** [comment]
Yep, that's cool.

I've archived the latest versions until this can be resolved.

**Comment by Bakermoose** [comment]
So because those files are missing that's why it doesn't work?  How do i get those files back?

**Comment by Xuerian** [comment]
> So because those files are missing that's why it doesn't work? How do i get those files back?

Just revert to the previous (latest available, now) version. There weren't any fixes as such, just preventing group from loading when it won't work, and bumping the TOC.

**Comment by Xuerian** [comment]
Apparently one of the recent bad versions was still the latest. It has been archived now.

**Comment by Shauren** [comment]
Broken releases are back on curseforge...

**Comment by Xuerian** [comment]
Yep, I don't know what's going on. Rather annoying, I have a curseforge ticket open.

In the meantime I have set all three recent files as alpha releases, since I can't figure out how to delete them (????)

**Comment by Xuerian** [comment]
Seems to be fixed now
