### ISSUE TITLE
Curseforge packaging broken

### ISSUE THREAD

**Issue by TheAzkas** [Xuerian/XLoot#37]
23x XLoot/XLoot.lua:58: attempt to index global 'XLootOptions' (a nil value)
[string "@XLoot/XLoot.lua"]:58: in function `ShowOptionPanel'
[string "@XLoot/XLoot.lua"]:156: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5422: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5368>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5074: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5073>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5110: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:363
 Enable = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:290
 NewModule = <function> defined @XLoot/XLoot.lua:23
 EnableModule = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @XLoot/XLoot.lua:29
 IterateEmbeds = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:438
 defaultModuleLibraries = <table> {
 }
 Localize = <function> defined @XLoot/localization.lua:18
 opt = <table> {
 }
 ShowOptionPanel = <function> defined @XLoot/XLoot.lua:53
 Deformat = <function> defined @XLoot/helpers.lua:158
 SetDefaultModulePrototype = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:405
 name = "XLoot"
 skinners = <table> {
 }
 IsEnabled = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 baseName = "XLoot"
 DisableModule = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:346
 InvertFormatString = <function> defined @XLoot/helpers.lua:129
 FancyPlayerName = <function> defined @XLoot/helpers.lua:91
 IsItemUpgrade = <function> defined @XLoot/helpers.lua:74
 slash_commands = <table> {
 }
 GetItemBindType = <function> defined @XLoot/helpers.lua:48
 CanEquipItem = <function> defined @XLoot/helpers.lua:59
 defaultModuleState = true
 defaultModulePrototype = <table> {
 }
 ApplySkinTweaks = <function> defined @XLoot/SKIN_TWEAKS.lua:4
 SkinsOnInitialize = <function> defined @XLoot/skins.lua:424
 RegisterMasqueTweak = <function> defined @XLoot/skins.lua:42
 IsModule = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:464
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:383
 MakeSkinner = <function> defined @XLoot/skins.lua:368
 RegisterSkin = <function> defined @XLoot/skins.lua:35
 SetEnabledState = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:420
 Skin = <table> {
 }
 enabledState = true
 OnEnable = <function> defined @XLoot/XLoot.lua:136
 OnInitialize = <function> defined @XLoot/XLoot.lua:125
 NewPrototype = <function> defined @XLoot/XLoot.lua:118
 GetName = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:275
 SetSkin = <function> defined @XLoot/skins.lua:466
 L = <table> {
 }
 IterateModules = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:433
 SetSlashCommand = <function> defined @XLoot/XLoot.lua:47
 ApplyOptions = <function> defined @XLoot/XLoot.lua:61
 CopperToString = <function> defined @XLoot/helpers.lua:15
 Stack = <table> {
 }
 Disable = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:310
 Prototype_New = <function> defined @XLoot/XLoot.lua:105
}
module = <table> {
 SetDefaultModuleLibraries = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:363
 Enable = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:290
 NewModule = <function> defined @XLoot/XLoot.lua:23
 EnableModule = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @XLoot/XLoot.lua:29
 IterateEmbeds =

**Comment by Xuerian** [comment]
Curseforge packaging is not functioning. Reinstall the latest available version on curse.

**Comment by TheAzkas** [comment]
have tried deleting and reinstalling multiple times from all sources i can find. same result. :(

**Comment by TheAzkas** [comment]
Works now thank you very much.
Now you just need to get around to fix the group loot in retail 😄

**Comment by Xuerian** [comment]
> Works now thank you very much. Now you just need to get around to fix the group loot in retail 😄

Pull requests are welcome :)

**Comment by Xuerian** [comment]
Seems to be packaging correctly now.
