### ISSUE TITLE
SL Beta: SetBackdrop errors.

### ISSUE THREAD

**Issue by VaporAPX** [Xuerian/XLoot#4]
Hi there, love this addon, saw that you updated it yesterday and grabbed it from here.  The loot monitor portion still throws the following error.

![xloot](https://user-images.githubusercontent.com/21989751/92989963-f9b1cf80-f48c-11ea-90b2-d630020d5995.jpg)

**Comment by Xuerian** [comment]
Yeah, the PRs were only for Frame. I'll try to get these addressed once I get my local repo settled.

**Comment by Xuerian** [comment]
Please try the latest version here.

**Comment by VaporAPX** [comment]
Seems to be working so far.  I'll post back again if I run into any issues.  Thank you for the effort and speedy fixes/response.  It's much appreciated.

**Comment by davidcraig** [comment]
Looking forward to this getting merged, currently getting these frame errors in game now :)

**Comment by Xuerian** [comment]
Should be live now.
