### ISSUE TITLE
LUA error with broken-3 SoD

### ISSUE THREAD

**Issue by GregoryGH** [Xuerian/XLoot#41]
2x Frame:RegisterEvent(): Frame:RegisterEvent(): Attempt to register unknown event "LOOT_HISTORY_UPDATE_DROP"
[string "=[C]"]: in function `RegisterEvent'
[string "@XLoot_Group/Group.lua"]:107: in function <XLoot_Group/Group.lua:99>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@XLoot/XLoot.lua"]:148: in function <XLoot/XLoot.lua:136>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by GregoryGH** [comment]
Any hope for a fix? Have to use 10.1-2b still.

**Comment by Xuerian** [comment]
Try: https://www.curseforge.com/wow/addons/xloot/files/5615459

**Comment by GregoryGH** [comment]
still 2 errors on login. SoD

1x Frame:RegisterEvent(): Frame:RegisterEvent(): Attempt to register unknown event "LOOT_HISTORY_UPDATE_DROP"
[string "=[C]"]: in function `RegisterEvent'
[string "@XLoot_Group/Group.lua"]:108: in function <XLoot_Group/Group.lua:100>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

1x XLoot/XLoot.lua:139: attempt to index global 'C_Addons' (a nil value)
[string "@XLoot/XLoot.lua"]:139: in function <XLoot/XLoot.lua:136>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by GregoryGH** [comment]
Btw, curse client only see broken-3 still, thats why i didnt try alpha 11-1, its doesnt marked for classic.

**Comment by Xuerian** [comment]
Right, I didn't actually push the changes since the packager wasn't working. Let's see if 11-2-alpha packages and works.

**Comment by GregoryGH** [comment]
still one lua error on login and it doesnt show 11-2-alpha in curse client for sod

1x Frame:RegisterEvent(): Frame:RegisterEvent(): Attempt to register unknown event "LOOT_HISTORY_UPDATE_DROP"
[string "=[C]"]: in function `RegisterEvent'
[string "@XLoot_Group/Group.lua"]:108: in function <XLoot_Group/Group.lua:100>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@XLoot/XLoot.lua"]:148: in function <XLoot/XLoot.lua:136>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by Xuerian** [comment]
Yeah, group is not going to work. It needs a rewrite

**Comment by GregoryGH** [comment]
Can you at least delete broken-2 and -3 for now so curse client doesnt show them as update?

**Comment by Xuerian** [comment]
> Can you at least delete broken-2 and -3 for now so curse client doesnt show them as update?

I still don't know how to get curseforge to label compatibility for all versions, so I'll try to manually tag 11-3 as latest for all versions.

**Comment by GregoryGH** [comment]
Loot roll window doesnt work with 11-4 in SoD. Had to revert to 10.1-2b still :(

**Comment by Xuerian** [comment]
Merging this in to #47
