### ISSUE TITLE
XLoot-11-2-alpha.zip LUA error with 11.0.2.56110

### ISSUE THREAD

**Issue by fraerie** [Xuerian/XLoot#43]
LUA Error while trying to loot in raid

5x XLoot_Group/Group.lua:227: attempt to index upvalue 'anchor' (a nil value)
[string "@XLoot_Group/Group.lua"]:227: in function `?'
[string "@XLoot/XLoot.lua"]:41: in function <XLoot/XLoot.lua:39>

Locals:
Skipped (In Encounter)

**Comment by Xuerian** [comment]
Group is not yet updated for new api changes, I will attempt to improve that notice and disabling in the future.
