### ISSUE TITLE
Addon seems to work but options are missing totally

### ISSUE THREAD

**Issue by bravetothebone** [Xuerian/XLoot#44]
I love this addons and cannot live without it <3

`1x XLoot/XLoot.lua:139: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@XLoot/XLoot.lua"]:139: in function <XLoot/XLoot.lua:136>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Rarity/Core/Collections.lua"]:63: in function `ScanToys'
[string "@Rarity/Core/Collections.lua"]:282: in function `ScanExistingItems'
[string "@Rarity/Core.lua"]:178: in function `DoEnable'
[string "@Rarity/Core.lua"]:150: in function <Rarity/Core.lua:149>
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
self = <table> {
 modules = <table> {
 }
 L_Monitor = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 opt = <table> {
 }
 L_Frame = <table> {
 }
 name = "XLoot"
 skinners = <table> {
 }
 orderedModules = <table> {
 }
 baseName = "XLoot"
 slash_commands = <table> {
 }
 defaultModuleState = true
 defaultModulePrototype = <table> {
 }
 db = <table> {
 }
 Skin = <table> {
 }
 enabledState = true
 L = <table> {
 }
 Stack = <table> {
 }
}
(for state) = <table> {
 1 = "XLoot1.0"
 2 = "XLootGroup"
 3 = "XLootMaster"
 4 = "XLootMonitor"
}
(for control) = 1
_ = 1
name = "XLoot1.0"
(*temporary) = nil
(*temporary) = "XLoot1.0"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"
`

**Comment by Xuerian** [comment]
Should be fixed in 11-3
