### ISSUE TITLE
TWW Beta - LUA error

### ISSUE THREAD

**Issue by Andf** [Xuerian/XLoot#45]
Hello!

Receiving the following error when trying Xloot on the beta servers:

5x XLoot_Options/Options.lua:441: attempt to call global 'GetItemQualityColor' (a nil value)
[string "@XLoot_Options/Options.lua"]:441: in function <XLoot_Options/Options.lua:98>
[string "=[C]"]: ?
[string "@Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@XLoot/XLoot.lua"]:148: in function <XLoot/XLoot.lua:136>
[string "=[C]"]: ?
[string "@Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 option_metadata = <table> {
 }
 modules = <table> {
 }
 baseName = "XLoot_Options"
 defaultModuleLibraries = <table> {
 }
 name = "XLoot_Options"
 orderedModules = <table> {
 }
 config = <table> {
 }
 enabledState = true
 BetterOptionsTypes = <table> {
 }
 BetterOptions = <table> {
 }
 moduleName = "Options"
 defaultModuleState = true
}
option_metadata = <table> {
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
}
BetterOptions = <table> {
 types = <table> {
 }
}
BetterOptionsTypes = <table> {
}
skins = <table> {
}
options = <table> {
 details = <table> {
 }
 skin_anchors = <table> {
 }
 skin = <table> {
 }
}
item_qualities = <table> {
}
(for index) = 0
(for limit) = 8
(for step) = 1
i = 0
(*temporary) = 4
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call global 'GetItemQualityColor' (a nil value)"
addon = <table> {
 option_metadata = <table> {
 }
 modules = <table> {
 }
 baseName = "XLoot_Options"
 defaultModuleLibraries = <table> {
 }
 name = "XLoot_Options"
 orderedModules = <table> {
 }
 config = <table> {
 }
 enabledState = true
 BetterOptionsTypes = <table> {
 }
 BetterOptions = <table> {
 }
 moduleName = "Options"
 defaultModuleState = true
}
update_throttle = Frame {
}
L = <table> {
 when_party = "In parties"
 Group = <table> {
 }
 desc_channel_auto = "Highest available"
 minimum_quality = "Minimum quality"
 when_never = "Never"
 offset = "Offset"
 up = "Up"
 font_size_loot = "Loot"
 font_sizes = "Sizes"
 when_solo = "Solo"
 Master = <table> {
 }
 Frame = <table> {
 }
 visible = "Visible"
 Monitor = <table> {
 }
 scale = "Scale"
 right = "Right"
 left = "Left"
 font_flag = "Flag"
 spacing = "Spacing"
 message_reloadui_warning = "|c2244dd22%s|r: Changing |c2244dd22%s|r requires you to reload your UI before continuing to play: |c2244dd22/reload ui|r"
 profile = "Profile"
 confirm_reset_profile = "This will reset all options for this profile. Are you sure?"
 font = "Font"
 when_group = "In groups"
 when_auto = "Automatic"
 when_always = "Always"
 bottom = "Bottom"
 top = "Top"
 font_size_quantity = "Quantity"
 alpha = "Opacity"
 width = "Width"
 Core = <table> {
 }
 items_own = "Own items"
 alignment = "Alignment"
 growth_direction = "Growth direction"
 items_others = "Others' items"
 padding = "Padding"
 down = "Down"
 when_raid = "In raids"
}

**Comment by Xuerian** [comment]
Should be fixed in 11-3

**Comment by Andf** [comment]
Morning and thanks for helping!

I have just tried 11-4 on beta and I got mixed results... previous errors seem gone, new ones popped up. Number 1 was nasty, it happened in a delve and only stopped when I left.

++++
1.
 
8237x XLoot_Monitor/Monitor.lua:195: attempt to call global 'GetItemCount' (a nil value)
[string "@XLoot_Monitor/Monitor.lua"]:195: in function <XLoot_Monitor/Monitor.lua:182>

Locals:
self = Frame {
}
elapsed = 0.006000
(for state) = <table> {
 1 = Button {
 }
}
(for control) = 1
i = 1
row = Button {
 BottomLeftCorner = Texture {
 }
 _skin_borders = <table> {
 }
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 total = FontString {
 }
 started = 0
 timeToTotal = 0.001000
 item = "|cffa335ee|Hitem:228073::::::::80:70:::::::::|h[Chunk of Companion Experience]|h|r"
 ilvl = FontString {
 }
 name = FontString {
 }
 _higlight_options = <table> {
 }
 text = FontString {
 }
 expires = 12
 icon = Texture {
 }
 TopRightCorner = Texture {
 }
 icon_frame = Frame {
 }
 _skin_options = <table> {
 }
 _highlights = <table> {
 }
 TopEdge = Texture {
 }
 Center = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 LeftEdge = Texture {
 }
 BottomRightCorner = Texture {
 }
}
ttt = nil
total = nil
(*temporary) = nil
(*temporary) = "|cffa335ee|Hitem:228073::::::::80:70:::::::::|h[Chunk of Companion Experience]|h|r"
(*temporary) = "attempt to call global 'GetItemCount' (a nil value)"
timer = 0.505000
stack = <table> {
 1 = Button {
 }
}
opt = <table> {
 threshold_own = 2
 use_altoholic = true
 show_currency = true
 show_coin = true
 fade_other = 7
 font_size_ilvl = 8
 anchor = <table> {
 }
 fade_own = 12
 font_size_quantity = 9
 gradients = false
 font_flag = "OUTLINE"
 show_totals = true
 font = "Fonts\2002B.TTF"
 show_ilvl = false
 totals_delay = 0.500000
 name_width = 50
 show_crafted = true
 threshold_other = 3
 font_size_loot = 10
}
addon = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 _skin_data = <table> {
 }
 name = "XLoot_Monitor"
 orderedModules = <table> {
 }
 db = <table> {
 }
 opt = <table> {
 }
 enabledState = true
 baseName = "XLoot_Monitor"
 moduleName = "Monitor"
 defaultModuleState = true
}

++++

2.

69x XLoot_Monitor/Monitor.lua:144: attempt to call global 'GetCoinIcon' (a nil value)
[string "@XLoot_Monitor/Monitor.lua"]:144: in function `?'
[string "@XLoot_Monitor/Monitor.lua"]:166: in function `func'
[string "@XLoot_Monitor/events.lua"]:51: in function <XLoot_Monitor/events.lua:49>
[string "@XLoot_Monitor/events.lua"]:181: in function <XLoot_Monitor/events.lua:180>
[string "=(tail call)"]: ?
[string "@XLoot_Monitor/events.lua"]:136: in function <XLoot_Monitor/events.lua:136>

Locals:
coin_string = "Xaamnis"
copper = 13506
(*temporary) = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 _skin_data = <table> {
 }
 name = "XLoot_Monitor"
 orderedModules = <table> {
 }
 db = <table> {
 }
 opt = <table> {
 }
 enabledState = true
 baseName = "XLoot_Monitor"
 moduleName = "Monitor"
 defaultModuleState = true
}
(*temporary) = nil
(*temporary) = 13506
(*temporary) = "attempt to call global 'GetCoinIcon' (a nil value)"
opt = <table> {
 threshold_own = 2
 use_altoholic = true
 show_currency = true
 show_coin = true
 fade_other = 7
 font_size_ilvl = 8
 anchor = <table> {
 }
 fade_own = 12
 font_size_loot = 10
 gradients = false
 font_flag = "OUTLINE"
 show_totals = true
 font = "Fonts\2002B.TTF"
 show_ilvl = false
 totals_delay = 0.500000
 name_width = 50
 show_crafted = true
 threshold_other = 3
 font_size_quantity = 9
}
addon = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 _skin_data = <table> {
 }
 name = "XLoot_Monitor"
 orderedModules = <table> {
 }
 db = <table> {
 }
 opt = <table> {
 }
 enabledState = true
 baseName = "XLoot_Monitor"
 moduleName = "Monitor"
 defaultModuleState = true
}

**Comment by Xuerian** [comment]
11-6 should have fixes for these when it's available. Let me know what else pops up.

**Comment by Andf** [comment]
It works, thanks!

**Comment by Andf** [comment]
.
