### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Lisann76** [Xuerian/XLoot#46]
Message: Interface/AddOns/XLoot/XLoot.lua:139: attempt to call global 'IsAddOnLoaded' (a nil value)
Time: Sat Aug 17 23:17:05 2024
Count: 1
Stack: Interface/AddOns/XLoot/XLoot.lua:139: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals: self = ExpansionLandingPage {
 overlay = <table> {
 }
 Overlay = Frame {
 }
}
newestOverlay = <table> {
}

**Comment by Xuerian** [comment]
Should be fixed in 11-3
