### ISSUE TITLE
Classicstyle loot frames after update for Cata Classic

### ISSUE THREAD

**Issue by NoirTheOne** [Xuerian/XLoot#48]
after the new Xloot Update i got the classic lootframes again in Cata classic

i checked my options but nothing changed there

**Comment by cleveroad-dmitry** [comment]
Can cofirm
SOD group loot broken a bit

**Comment by DaveMate93** [comment]
Yeah, something is not working right in both the latest and previous versions. It throws out errors and disables XLootGroup altogether.

I have downgraded to “10.1-2b” and all seems to be fine for now.

**Comment by NoirTheOne** [comment]
but i wonder couse the previos version worked till the update.

**Comment by Xuerian** [comment]
Working on this in #47
