### ISSUE TITLE
XLoot Group Loot tab no longer exists

### ISSUE THREAD

**Issue by Aarali** [Xuerian/XLoot#49]
As of August 18th the Group loot tab in Xloot is gone and you can no longer see what other people select for items that drop. Reverting to older versions has worked either

**Comment by Xuerian** [comment]
Thanks for your report. Dealing with this in #

**Comment by Aarali** [comment]
My sincerest apologies for a duplicate and you have my deepest thanks for this addon

**Comment by Xuerian** [comment]
> My sincerest apologies for a duplicate and you have my deepest thanks for this addon

Not a problem. Glad you enjoy it.

**Comment by Aarali** [comment]
Got the latest version you just sent out. Unfortunately the issue persists :/

**Comment by Xuerian** [comment]
What expansion are you playing?

**Comment by Aarali** [comment]
Classic Era. Apologies I also see you merged everything into #47

**Comment by Xuerian** [comment]
Sure, but there's also a report there that 11-7 works there. Did you re-enable group after the previous version disabled itself? Are you getting any errors?

**Comment by Aarali** [comment]
I tried earlier versions and the latest with relaunches. I see a confirmed report for cata classic but not classic era. Not getting any errors

**Comment by Aarali** [comment]
Did a couple more launches to check and I don't even have the option to enable anything for group

**Comment by Xuerian** [comment]
Ok. I haven't played since classic anything came out so I really don't have a good grip on what the UI situation is.

In your addon list at character select, group is present and checked?

**Comment by Aarali** [comment]
You sexy individual. I am unsure why that didn't cross my mind to check there. It is there and enabled again. Thank you

**Comment by Xuerian** [comment]
Glad it was an easy fix!
