### ISSUE TITLE
904 alpha bug

### ISSUE THREAD

**Issue by Addonman** [Xuerian/XLoot#5]
Message: ..\AddOns\XLoot_Frame\Frame.lua line 253:
   'do' expected near 'then'
Debug:
   [string "=(tail call)"]: ?
   [string "@RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149:
      ...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147
   [string "=[C]"]: ?

**Comment by Xuerian** [comment]
Should be fixed.
