### ISSUE TITLE
Xloot Group doesnt work in SoD

### ISSUE THREAD

**Issue by GregoryGH** [Xuerian/XLoot#50]
**Addon version:**

Any up to 11-7. Last working version is 10.1-2b

**Game version:**

SoD

**Description:**

XLoot frames doesnt appear, just regular blizzard frames

**Errors:**

None

**Comment by Feirlane** [comment]
Previous versions of XLoot were disabling the Group module from the addon list in SoD completely, which means even if you update, your addon remains disabled even if you update to a supported version (please don't do that again).

Update your xloot, go to the loaded addons list, and enable `XLoot Group` again, that should do the trick.

**Comment by GregoryGH** [comment]
oh, thanks. seems that was an issue :)

**Comment by Xuerian** [comment]
> Previous versions of XLoot were disabling the Group module from the addon list in SoD completely, which means even if you update, your addon remains disabled even if you update to a supported version (please don't do that again).
> 
> Update your xloot, go to the loaded addons list, and enable `XLoot Group` again, that should do the trick.

Thank you for sharing the solution.

As far as disabling it, I don't know what I'll do going forward. It printed a message before, and it was ignored in reports when it didn't disable itself. It printed a message when disabling, and was ignored. Print too much, and people also get annoyed. 

*Shrug*

**Comment by Feirlane** [comment]
I think [this](https://github.com/Xuerian/XLoot/commit/697bf1eb3d3d4681fca938cca4fe27c75473bd79) does the trick indeed. This way an updated version of the addon that actually supports the client version would "re-enable" the addon. Thanks for the change!
