### ISSUE TITLE
Allow installation from GitHub to WowUp

### ISSUE THREAD

**Issue by raptormama** [Xuerian/XLoot#6]
Unable to install via WoWUp: "A valid zip file is required to be in the release in order for WowUp to download it". Can this be added to the github page?

See https://github.com/BigWigsMods/packager for details (hah!).

**Comment by Xuerian** [comment]
Thanks for the suggestion, but I have no reason to support WoWUp.

I certainly have annoyances with CF/OW but it's functional.

**Comment by WanderingFox** [comment]
@Xuerian you could also just cross-host on [wago.io](https://addons.wago.io/) which also has author compensation and uses the same packaging system as curse iirc. In most cases it's as simple as just linking your github account and adding the addon.

**Comment by Xuerian** [comment]
I've updated the WoWInterface upload. WoWup should also be able to pull from that.
