### ISSUE TITLE
wowup integration

### ISSUE THREAD

**Issue by YoanKECH** [Xuerian/XLoot#7]
Hello, 

is that possible to fix it for wowup - git link ? 
At the moment reading 'assets' seems undefined

Thanks

**Comment by Xuerian** [comment]
I don't use WoWUp. Others who have requested it say it works after I updated the WoWI upload. Please confirm if you can switch sources or something and use that.

I keep hearing how bad CF is and how great wowup is but so far it's only caused me annoyance.

**Comment by YoanKECH** [comment]
when trying to integrate it says : Cannot read properties of undefined (reading 'assets')

**Comment by lgrano** [comment]
I understand your frustration with WoWUP, the situation with Overwolf/CF and WoWUP is unfortunately, WoWInterface download does work, the issue some people are having is that WoWI does not  have good APIs to manage addons, for example WoWUP cannot search correctly from WoWI or figured out on its own when a addon such as XLoot support multiple clients on a single download.

A solution could be uploading your addon to Wago for example, that would fix all WoWUP issues. The reason people dont like CF anymore has to do with Overwolf, their client used to have a lot of adware and bloat as hidden install, personally id prefer to avoid installing anything that comes from that company on my pc.

**Comment by Xuerian** [comment]
I'd rather not go through submitting all the relevant information that Wago expects, I have similar feelings to that that apparently a large amount of people feel towards the curseforge client.

I've voluntarily used it to manage minecraft installs for a while.

If you've donated you're welcome to pursue this in an email with me.

**Comment by YoanKECH** [comment]
WOWI update has been made, agree to close. Solution Fixed

**Comment by InfiniteIce2** [comment]
Here is an alternate solution for the CurseForge/WowUp issues -

[https://github.com/WowUp/WowUp.CF/releases](https://github.com/WowUp/WowUp.CF/releases)

Works for both classic & retail,  Download a release, don't compile from source (read the wowup.cf main page if you are going to try compiling anyway).  

<details> **<summary>  Screenshot. Note "View on Curse" in bottom right.</summary>**
<p>
<img width="683" height="804" alt="Image" src="https://github.com/user-attachments/assets/b4135372-6f96-42c9-ad8d-8e28407fb7a6" />
</p>
</details> 
Cheers.
