### ISSUE TITLE
WotlK

### ISSUE THREAD

**Issue by Nitti2909** [Xuerian/XLoot#8]
Any plans to update it to WotlK?
(Plz, been using this since day one, cannot live without my Xloot...).

**Comment by Xuerian** [comment]
I don't have access to classic. If you can provide me information as to what's not working and what errors you get, I can try to fix it.

**Comment by Nitti2909** [comment]
It seems to be working fine so far, but its not listed as a 3.4.0 addon on Curse.

**Comment by Xuerian** [comment]
I've bumped TOC versions to what I think are correct. Due to the overwolf.. problems.. the last time I tried to update to the new toc formats they may not be entirely what they should be. 

Please let me know if it seems to work.

**Comment by sanfair** [comment]
Just updated through CurseForge App.  Looks good. Thank you
![image](https://user-images.githubusercontent.com/20707205/189493335-069b0721-1f2d-426d-9d83-692cf64fb0ec.png)
